# Hydra configuration for logging. Customised the folder
hydra:
  run:
    dir: hydra_logs/${now:%Y-%m-%d}/${now:%H-%M-%S}

videos:
  video_filename: "pickleball_highlights.mp4"
  input_video_folder: "data/input_videos/"
  output_video_folder: "data/output_videos/"

court_keypoints:
  court_keypoints_folder: "data/court_keypoints/"
  court_keypoints_filename: "court_keypoints_{video_filename_stem}.json"

models:
  model_folder: "data/artifacts/models/"
  yolo12x: "yolo12x.pt"
  roboflow_ball_model_id: "pickleball-vision/6"

stubs:
  stub_folder: "data/artifacts/tracker_stubs/"
  player_detections_stub: "player_detections_{video_filename_stem}.pkl"
  ball_detections_stub: "ball_detections_{video_filename_stem}.pkl"

court_dimensions:
  court_width_m: 6.1  # Width of a pickleball court in meters
  court_length_m: 13.41  # Length of a pickleball court in meters
  kitchen_line_from_net_m: 2.13  # Distance from net to kitchen line in meters
  kitchen_line_from_baseline_m: 4.57  # Distance from baseline to kitchen line in meters
  side_line_from_center_m: 3.05  # Distance from center to side line in meters
  net_height_m: 0.914  # Height of the net at the center in meters

player_details:
  player_1:
    height: 1.75
    name: "Player 1"
  player_2:
    height: 1.80
    name: "Player 2"
  player_3:
    height: 1.70
    name: "Player 3"
  player_4:
    height: 1.85
    name: "Player 4"