# Hydra configuration for logging. Customised the folder
hydra:
  run:
    dir: hydra_logs/${now:%Y-%m-%d}/${now:%H-%M-%S}

videos:
  video_filename: "pickleball_highlights.mp4"
  input_video_folder: "data/input_videos/"
  output_video_folder: "data/output_videos/"

court_keypoints:
  court_keypoints_folder: "data/court_keypoints/"
  court_keypoints_filename: "court_keypoints_{video_filename_stem}.json"

models:
  model_folder: "data/artifacts/models/"
  yolo12x: "yolo12x.pt"
  roboflow_ball_model_id: "pickleball-vision/6"

stubs:
  stub_folder: "data/artifacts/tracker_stubs/"
  player_detections_stub: "player_detections_{video_filename_stem}.pkl"
  ball_detections_stub: "ball_detections_{video_filename_stem}.pkl"

# Height is in feet
player_details:
  player_1:
    height: 5.74
    name: "Parenteau"
  player_2:
    height: 5.92
    name: "McGuffin"
  player_3:
    height: 5.58
    name: "Todd"
  player_4:
    height: 6.07
    name: "Newman"