# Hydra configuration for logging. Customised the folder
hydra:
  run:
    dir: hydra_logs/${now:%Y-%m-%d}/${now:%H-%M-%S}

videos:
  video_filename: "pickleball_highlights.mp4"
  input_video_folder: "data/input_videos/"
  output_video_folder: "data/output_videos/"

court_keypoints:
  court_keypoints_folder: "data/court_keypoints/"
  court_keypoints_filename: "court_keypoints_{video_filename_stem}.json"

models:
  model_folder: "data/artifacts/models/"
  yolo12x: "yolo12x.pt"
  roboflow_ball_model_id: "pickleball-vision/6"

stubs:
  stub_folder: "data/artifacts/tracker_stubs/"
  player_detections_stub: "player_detections_{video_filename_stem}.pkl"
  ball_detections_stub: "ball_detections_{video_filename_stem}.pkl"

# Height is in feet. player_id used for showing the name of players on annotation. player_id is input manually for now.
player_details:
  player_1:
    height: 5.74
    name: "Parenteau"
    player_id: 1
  player_2:
    height: 5.92
    name: "McGuffin"
    player_id: 2
  player_3:
    height: 5.58
    name: "Todd"
    player_id: 9
  player_4:
    height: 6.07
    name: "Newman"
    player_id: 15

# Tracker configuration
player_tracker:
  tracker_type: bytetrack
  track_high_thresh: 0.5   # Detection confidence threshold for confirmed tracks
  track_low_thresh: 0.2     # Detection confidence threshold for tentative (low-score) tracks
  new_track_thresh: 0.6 # Minimum detection score to initialize a new track
  track_buffer: 60    # Number of frames before a lost track is removed (crucial for re-identification)
  match_thresh: 0.8   # IoU threshold for matching confirmed tracks
  fuse_score: True  # Whether to use detection scores to refine track confidence (helps reduce false positives)